FROM python:3.7-buster
RUN mkdir -p /opt/app
COPY . /opt/app
WORKDIR /opt/app
RUN chmod +x /opt/app/config/*
RUN pip install --default-timeout=1000 -r /opt/app/requirements/production_pi.txt
RUN mkdir -p /tmp/probetspp/static
RUN chmod -R 775 /tmp/probetspp/static
ENV ALLOWED_HOSTS='*'
CMD ["sh", "config/entrypoint.sh"]