# Generated by Django 3.1.4 on 2021-01-17 07:14

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('short_name', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.SmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('total_games', models.IntegerField(default=0)),
                ('won_games', models.IntegerField(default=0)),
                ('lost_games', models.IntegerField(default=0)),
                ('won_sets', models.IntegerField(default=0)),
                ('lost_sets', models.IntegerField(default=0)),
                ('won_points', models.IntegerField(default=0)),
                ('lost_points', models.IntegerField(default=0)),
                ('back_to_win', models.IntegerField(default=0)),
                ('back_to_lose', models.IntegerField(default=0)),
                ('games_sold', models.IntegerField(default=0)),
                ('total_predictions', models.IntegerField(default=0)),
                ('won_predictions', models.IntegerField(default=0)),
                ('lost_predictions', models.IntegerField(default=0)),
                ('confidence_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stats', to='games.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.CharField(max_length=50)),
                ('gender', models.SmallIntegerField(default=1)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'unique_together': {('external_id', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.CharField(max_length=150, unique=True)),
                ('start_dt', models.DateTimeField()),
                ('status', models.SmallIntegerField(default=-1)),
                ('home_score', models.SmallIntegerField(default=0)),
                ('away_score', models.SmallIntegerField(default=0)),
                ('line_score', models.JSONField(null=True)),
                ('away_player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_games', to='games.player')),
                ('home_player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_games', to='games.player')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_visitor', to='games.league')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
