# Generated by Django 3.1.4 on 2021-01-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='a_odds',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='h_odds',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
