# Generated by Django 3.1.4 on 2021-02-01 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210128_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='games.league'),
        ),
    ]
