"""
Django settings for probets project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import sys
from os import environ
from os.path import abspath, basename, dirname, join, normpath

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DJANGO_ROOT = dirname(dirname(abspath(__file__)))

PROJECT_ROOT = dirname(DJANGO_ROOT)

SECRET_KEY = environ.get(
    'SECRET_KEY',
    'abcdefghijklmnopqrstuvwxyz0123456789!$%&()=+-_'
)

SITE_NAME = basename(DJANGO_ROOT)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

PROJECT_TEMPLATES = [
    join(BASE_DIR, 'templates'),
]

sys.path.append(normpath(join(PROJECT_ROOT, 'apps')))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

ALLOWED_HOSTS = ['*']

DEFAULT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites'
]

THIRD_PARTY_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'django_q',
    'dj_rest_auth',
    'storages',
]

# Application definition
LOCAL_APPS = [
    'apps.core',
    'apps.data',
    'apps.games',
    'apps.predictions'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'probetspp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': PROJECT_TEMPLATES,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.static',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'probetspp.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

TIME_ZONE = environ.get(
    'TIME_ZONE',
    'America/Bogota'
)

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = join(PROJECT_ROOT, 'static')
STATIC_ROOT = '/tmp/probetspp/static'

MEDIA_ROOT = join(PROJECT_ROOT, 'media')

# STATICFILES_DIRS = [
#   os.path.join(BASE_DIR, "static"),
# ]

TOKEN_DURATION = int(environ.get('TOKEN_DURATION', 10000))

INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + LOCAL_APPS  # noqa

REST_SESSION_LOGIN = True
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
SITE_ID = 1
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_VERIFICATION = 'optional'

REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'apps.access.serializers.RegisterSerializer'
}
# REST_AUTH_TOKEN_CREATOR = 'apps.access.services.generate_token2'
# REST_USE_JWT = True
# JWT_AUTH_COOKIE = 'auth'

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'apps.utils.handlers.exception_errors_format_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': (
        'rest_framework.pagination.LimitOffsetPagination'
    ),
    # 'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}

SWAGGER_SETTINGS = {
    'LOGIN_URL': 'login',
    'LOGOUT_URL': 'logout',
}

LOGGING = {
    'version': 1,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s :: %(asctime)s :: '
                      '%(name)s :: %(process)d %(thread)d :: %(message)s'
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'apps.core': {
            'handlers': ['console'],
            'level': environ.get('LOG_LEVEL', 'INFO')
        },
        'apps.data': {
            'handlers': ['console'],
            'level': environ.get('LOG_LEVEL', 'INFO')
        },
        'apps.flashscore': {
            'handlers': ['console'],
            'level': environ.get('LOG_LEVEL', 'INFO')
        },
        'apps.games': {
            'handlers': ['console'],
            'level': environ.get('LOG_LEVEL', 'INFO')
        },
        'apps.predictions': {
            'handlers': ['console'],
            'level': environ.get('LOG_LEVEL', 'INFO')
        },
        'apps.third_parties': {
            'handlers': ['console'],
            'level': environ.get('LOG_LEVEL', 'INFO')
        }
    }
}

Q_CLUSTER = {
    "name": "probets",
    "orm": "default",  # Use Django's ORM + database for broker
    "timeout": 300,
    "retry": 300,
    "max_attempts": 1
}
# AWS CREDENTIALS
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
