from os import getenv


TELEGRAM_PHONE_NUMBER = getenv('TELEGRAM_PHONE_NUMBER')
TELEGRAM_API_ID = int(getenv('TELEGRAM_API_ID', 0))
TELEGRAM_API_HASH = getenv('TELEGRAM_API_HASH')
TELEGRAM_CHANNEL_NAME = getenv('TELEGRAM_CHANNEL_NAME')
