# Generated by Django 3.1.4 on 2021-01-17 07:14

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataWeights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('wt_games', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18)),
                ('wt_sets', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18)),
                ('wt_points', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18)),
                ('wt_games_sold', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18)),
                ('wt_predictions', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18)),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_profile', to='games.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('min_wt_p_diff', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='min wt player diff')),
                ('h_wt_score', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='home wt score')),
                ('a_wt_score', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='away wt score')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data', to='games.game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
