# Generated by Django 3.1.4 on 2021-01-22 02:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('p_wt_diff', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='min player wt diff')),
                ('h2h_wt_diff', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='min h2h wt diff')),
                ('lg_wt_diff', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='min last games wt diff')),
                ('d_opp_wt_diff', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='min direct opponents wt diff')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataWeights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('wt_games', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18)),
                ('wt_sets', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18)),
                ('wt_points', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18)),
                ('wt_games_sold', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18)),
                ('wt_predictions', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18)),
                ('wt_h2h', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18)),
                ('wt_last_games', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18)),
                ('wt_direct_opponents', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18)),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_profile', to='games.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('h_wt_score', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='home wt score')),
                ('a_wt_score', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='away wt score')),
                ('h_h2h_wins', models.IntegerField(default=0, verbose_name='home h2h wins')),
                ('a_h2h_wins', models.IntegerField(default=0, verbose_name='away h2h wins')),
                ('t_h2h', models.IntegerField(default=0, verbose_name='total h2h games')),
                ('h_h2h_wt_score', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='away h2h wt score')),
                ('a_h2h_wt_score', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='away h2h wt score')),
                ('h_lg_wt_score', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='home last games wt score')),
                ('a_lg_wt_score', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='away last games wt score')),
                ('h_d_opp_wt_score', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='home direct opponents wt score')),
                ('a_d_opp_wt_score', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='away direct opponents wt score')),
                ('confidence', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=18, verbose_name='confidence prediction')),
                ('acceptance_value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_games', to='data.acceptancevalue')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data', to='games.game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
