# Generated by Django 3.1.4 on 2021-01-19 01:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagame',
            name='a_d_opp_wt_score',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='away direct opponents wt score'),
        ),
        migrations.AddField(
            model_name='datagame',
            name='a_h2h_wt_score',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='away h2h wt score'),
        ),
        migrations.AddField(
            model_name='datagame',
            name='a_l_g_wt_score',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='away last games wt score'),
        ),
        migrations.AddField(
            model_name='datagame',
            name='h_d_opp_wt_score',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='home direct opponents wt score'),
        ),
        migrations.AddField(
            model_name='datagame',
            name='h_h2h_wt_score',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='away h2h wt score'),
        ),
        migrations.AddField(
            model_name='datagame',
            name='h_l_g_wt_score',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='home last games wt score'),
        ),
        migrations.AddField(
            model_name='datagame',
            name='min_d_opp_wt_diff',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='min direct opponents wt diff'),
        ),
        migrations.AddField(
            model_name='datagame',
            name='min_h2h_wt_diff',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='min h2h wt diff'),
        ),
        migrations.AddField(
            model_name='datagame',
            name='min_l_g_wt_diff',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='min last games wt diff'),
        ),
        migrations.AddField(
            model_name='dataweights',
            name='wt_direct_opponents',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='dataweights',
            name='wt_h2h',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='dataweights',
            name='wt_last_games',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18),
        ),
    ]
