# Generated by Django 3.1.4 on 2021-01-21 01:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210118_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('p_wt_diff', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='min player wt diff')),
                ('h2h_wt_diff', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='min h2h wt diff')),
                ('l_g_wt_diff', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='min last games wt diff')),
                ('d_opp_wt_diff', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='min direct opponents wt diff')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='datagame',
            name='min_wt_p_diff',
        ),
        migrations.AddField(
            model_name='datagame',
            name='min_p_wt_diff',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='min player wt diff'),
        ),
    ]
