# Generated by Django 3.1.4 on 2021-01-21 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210120_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datagame',
            name='min_d_opp_wt_diff',
        ),
        migrations.RemoveField(
            model_name='datagame',
            name='min_h2h_wt_diff',
        ),
        migrations.RemoveField(
            model_name='datagame',
            name='min_l_g_wt_diff',
        ),
        migrations.RemoveField(
            model_name='datagame',
            name='min_p_wt_diff',
        ),
        migrations.AddField(
            model_name='datagame',
            name='acceptance_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_games', to='data.acceptancevalue'),
            preserve_default=False,
        ),
    ]
